# Generated by Django 3.2.4 on 2021-06-22 13:06
# deletado o atributo email do Perfil
# e incluído o atributo turno no Turma
#
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formaaprendizagem',
            options={'verbose_name': 'Forma de Aprendizagem'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(blank=True, choices=[('Matutino', 'Matutino'), (
                'Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], max_length=15, null=True),
        ),
    ]
