# Generated by Django 3.2.4 on 2021-06-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20210622_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
