# Generated by Django 3.2.4 on 2021-06-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_delete_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estilo',
        ),
        migrations.DeleteModel(
            name='FormaAprendizagem',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='opcao',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='tentativa',
        ),
        migrations.RemoveField(
            model_name='tentativa',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='tentativa',
            name='teste',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='questionario',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='turma',
        ),
        migrations.DeleteModel(
            name='Opcao',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
        migrations.DeleteModel(
            name='Questionario',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
        migrations.DeleteModel(
            name='Tentativa',
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
