# Generated by Django 3.2.4 on 2021-07-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20210709_0459'),
        ('cadastros', '0004_auto_20210626_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='endereco',
            field=models.CharField(max_length=100, null=True, verbose_name='Endereço'),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
