# Generated by Django 3.2.4 on 2021-07-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20210709_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Instituição de Ensino', 'verbose_name_plural': 'Instituções de Ensinos'},
        ),
    ]
