# Generated by Django 3.2.4 on 2021-08-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_auto_20210815_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='ra',
        ),
    ]
