# Generated by Django 3.2.4 on 2021-10-28 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0011_auto_20211027_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
