# Generated by Django 3.2.4 on 2021-10-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20211010_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='grupo',
        ),
    ]
