# Generated by Django 3.2.4 on 2021-10-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20211022_1758'),
        ('usuarios', '0007_remove_perfil_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.turma'),
        ),
    ]
