# Generated by Django 3.2.4 on 2021-10-23 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20211022_1758'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0008_perfil_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='turma',
        ),
        migrations.CreateModel(
            name='UsuarioTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.turma')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário com Turma',
                'verbose_name_plural': 'Usuários com Turmas',
            },
        ),
    ]
