# Generated by Django 3.2.4 on 2021-10-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20211023_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioTurma',
        ),
    ]
