# Generated by Django 3.2.4 on 2021-10-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20211023_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='usuarioTurma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarioturma'),
        ),
    ]
