# Generated by Django 3.2.4 on 2021-06-26 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0004_auto_20210626_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=300, verbose_name='Descrição')),
                ('recomendacao', models.TextField(max_length=300, verbose_name='Recomendação')),
            ],
            options={
                'verbose_name': 'Estilo',
            },
        ),
        migrations.CreateModel(
            name='FormaAprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=300, verbose_name='Descrição')),
                ('recomendacao', models.TextField(max_length=300, verbose_name='Recomendação')),
            ],
            options={
                'verbose_name': 'Forma de Aprendizagem',
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('ordem', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Opção',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Questão',
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Questionário',
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descriçãos')),
                ('data', models.DateField(auto_now_add=True)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('chave_acesso', models.CharField(blank=True, max_length=30, null=True, verbose_name='Chave de Acesso')),
                ('ativo', models.BooleanField(default=False)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='KolbStyleTeste.questionario')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cadastros.turma')),
            ],
            options={
                'verbose_name': 'Teste',
            },
        ),
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('concluiu', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tentativa_alunos', to=settings.AUTH_USER_MODEL)),
                ('teste', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testes', to='KolbStyleTeste.teste')),
            ],
            options={
                'verbose_name': 'Tentativa',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to=settings.AUTH_USER_MODEL)),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcaos', to='KolbStyleTeste.opcao', verbose_name='Opção')),
                ('tentativa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KolbStyleTeste.tentativa', verbose_name='tentativas')),
            ],
            options={
                'verbose_name': 'Resposta',
            },
        ),
        migrations.AddField(
            model_name='opcao',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questaos', to='KolbStyleTeste.questao', verbose_name='Questão'),
        ),
        migrations.AlterUniqueTogether(
            name='opcao',
            unique_together={('descricao', 'questao')},
        ),
    ]
