# Generated by Django 3.2.4 on 2021-06-28 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KolbStyleTeste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='ordem',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='questionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questao_questionarios', to='KolbStyleTeste.questionario'),
        ),
    ]
