# Generated by Django 3.2.4 on 2021-07-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KolbStyleTeste', '0003_auto_20210628_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcao',
            options={'ordering': ['ordem'], 'verbose_name': 'Opção'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'ordering': ['ordem'], 'verbose_name': 'Questão'},
        ),
        migrations.AlterUniqueTogether(
            name='opcao',
            unique_together={('ordem', 'questao')},
        ),
        migrations.AlterUniqueTogether(
            name='questao',
            unique_together={('questionario', 'ordem')},
        ),
    ]
