# Generated by Django 3.2.4 on 2021-07-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KolbStyleTeste', '0004_auto_20210709_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formaaprendizagem',
            options={'verbose_name': 'Forma de Aprendizagem', 'verbose_name_plural': 'Formas de Aprendizagens'},
        ),
        migrations.AlterModelOptions(
            name='opcao',
            options={'ordering': ['ordem'], 'verbose_name': 'Opção', 'verbose_name_plural': 'Opções'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'ordering': ['ordem'], 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
    ]
