# Generated by Django 3.2.4 on 2021-07-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KolbStyleTeste', '0005_auto_20210709_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='tentativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KolbStyleTeste.tentativa', verbose_name='tentativas'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='valor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tentativa',
            name='concluiu',
            field=models.BooleanField(default=True),
        ),
    ]
