# Generated by Django 3.2.4 on 2021-07-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KolbStyleTeste', '0006_auto_20210715_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='valor',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
