# Generated by Django 3.2.5 on 2021-08-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KolbStyleTeste', '0008_alter_tentativa_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='forma_aprendizagem',
            field=models.ForeignKey(default=1, help_text='As respostas dessa opção serão somadas para calcular o valor da forma de aprendizagem selecionada.', on_delete=django.db.models.deletion.PROTECT, to='KolbStyleTeste.formaaprendizagem'),
            preserve_default=False,
        ),
    ]
