# Generated by Django 3.2.5 on 2021-08-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KolbStyleTeste', '0011_auto_20210814_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tentativa',
            name='aluno',
        ),
    ]
