# Generated by Django 3.2.4 on 2021-08-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KolbStyleTeste', '0013_alter_teste_chave_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
