# Generated by Django 3.2.4 on 2021-08-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KolbStyleTeste', '0014_alter_teste_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='chave_acesso',
            field=models.CharField(help_text='Informe uma chave de acesso que também deverá ser fornecida aos usuários que irão responder o teste criado por você.', max_length=30, unique=True, verbose_name='Chave de Acesso'),
        ),
    ]
