# Generated by Django 3.2.4 on 2021-09-02 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_remove_turma_ra'),
        ('KolbStyleTeste', '0015_alter_teste_chave_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativa',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.turma'),
        ),
    ]
