# Generated by Django 3.2.4 on 2021-09-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KolbStyleTeste', '0016_tentativa_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativa',
            name='estilo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='KolbStyleTeste.estilo'),
        ),
    ]
