# Generated by Django 3.2.4 on 2021-09-23 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_remove_turma_ra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KolbStyleTeste', '0017_tentativa_estilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tentativa',
            name='estilo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KolbStyleTeste.estilo'),
        ),
        migrations.AlterField(
            model_name='tentativa',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.turma'),
        ),
        migrations.AlterField(
            model_name='tentativa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
