# Generated by Django 3.2.4 on 2021-09-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KolbStyleTeste', '0018_auto_20210923_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
