# Generated by Django 3.2.4 on 2021-10-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KolbStyleTeste', '0019_alter_opcao_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcao',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='opcao',
            name='video',
        ),
        migrations.RemoveField(
            model_name='tentativa',
            name='concluiu',
        ),
        migrations.AlterField(
            model_name='opcao',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
