# Generated by Django 3.2.4 on 2021-10-06 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KolbStyleTeste', '0020_auto_20211005_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estilo',
            name='descricao',
            field=models.TextField(max_length=800, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='estilo',
            name='recomendacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Recomendação'),
        ),
        migrations.AlterField(
            model_name='formaaprendizagem',
            name='descricao',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='formaaprendizagem',
            name='recomendacao',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Recomendação'),
        ),
        migrations.AlterField(
            model_name='tentativa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
