# Generated by Django 3.2.4 on 2021-10-30 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_delete_usuarioturma'),
        ('KolbStyleTeste', '0021_auto_20211006_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativa',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
    ]
